message(STATUS "CMAKE_PREFIX_PATH: ${CMAKE_PREFIX_PATH}")
string(REPLACE " " ";" CMAKE_PREFIX_PATH "${CMAKE_PREFIX_PATH}")

include(GetPrerequisites)
get_prerequisites(${LOGOPRISM_TARGET} LOGOPRISM_DEPENDENCIES 1 1 ${CMAKE_BINARY_DIR} "")

foreach(LOGOPRISM_DEPENDENCY ${LOGOPRISM_DEPENDENCIES})
  set(LOGOPRISM_DLL "LOGOPRISM_DLL-NOTFOUND")
  find_program(LOGOPRISM_DLL "${LOGOPRISM_DEPENDENCY}")
  message(STATUS "${LOGOPRISM_DEPENDENCY}: ${LOGOPRISM_DLL}")
  if(LOGOPRISM_DLL)
    file(COPY ${LOGOPRISM_DLL} DESTINATION ${LOGOPRISM_TARGET_PATH})
  endif()
endforeach()
